# Generated by Django 3.1.14 on 2026-03-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': '电影类型', 'verbose_name_plural': '电影类型'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影信息', 'verbose_name_plural': '电影信息'},
        ),
        migrations.AlterModelOptions(
            name='movie_hot',
            options={'verbose_name': '最热电影', 'verbose_name_plural': '最热电影'},
        ),
        migrations.AlterModelOptions(
            name='movie_rating',
            options={'verbose_name': '电影评分信息', 'verbose_name_plural': '电影评分信息'},
        ),
        migrations.AlterModelOptions(
            name='movie_similarity',
            options={'verbose_name': '电影相似度', 'verbose_name_plural': '电影相似度'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否管理员'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=512, verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=256, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie.Genre', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(verbose_name='imdb_id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='intro',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_similarity',
            field=models.ManyToManyField(through='movie.Movie_similarity', to='movie.Movie', verbose_name='相似电影'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_time',
            field=models.CharField(blank=True, max_length=256, verbose_name='发行时间'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.CharField(blank=True, max_length=256, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.CharField(blank=True, max_length=256, verbose_name='编剧'),
        ),
        migrations.AlterField(
            model_name='movie_hot',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='电影名'),
        ),
        migrations.AlterField(
            model_name='movie_hot',
            name='rating_number',
            field=models.IntegerField(verbose_name='评分人数'),
        ),
        migrations.AlterField(
            model_name='movie_rating',
            name='comment',
            field=models.TextField(blank=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='movie_rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='电影'),
        ),
        migrations.AlterField(
            model_name='movie_rating',
            name='score',
            field=models.FloatField(verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='movie_rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='movie_similarity',
            name='movie_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_source', to='movie.movie', verbose_name='来源电影'),
        ),
        migrations.AlterField(
            model_name='movie_similarity',
            name='movie_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_target', to='movie.movie', verbose_name='目标电影'),
        ),
        migrations.AlterField(
            model_name='movie_similarity',
            name='similarity',
            field=models.FloatField(verbose_name='相似度'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
